/**
 * File generated by the Figma Token Engine
 * Do not edit directly
 */

export const TYPO_BLACK = "#2d2d2d";
export const BRAND_DN = "#15307a";
export const BRAND_DNTEST = "#39415b";
export const GRAY_80 = "#ccc";
export const GRAY_90 = "#e6e6e6";
export const GRAY_95 = "#f2f2f2";